server:
  port: 9028
person:
  name: 张丹明
  age: 34
  hobby:
    - skip
    - movie
    - girls
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123

